### ISSUE TITLE
Battle Garegga - A+B+C Button Binding

### ISSUE THREAD

**Issue by luke86** [MiSTer-devel/Arcade-Raizing_MiSTer#10]
In the ship selection there is a way to choose the "Speed Up and Shot Power Type" variant of the currently marked ship if you press A+B+C button at the same time.

Can we maybe have a binding for one button that presses all these 3 buttons? The Neo Geo core has such a binding for easy cheat menu access.

**Comment by zakk4223** [comment]
The MRA in this repo lets you use the start button to select the A+B+C ship
https://github.com/zakk4223/battle-garegga-patches/tree/master/mister

Keep the stage edit dip disabled if you don't want all the on-screen 'gadgets'.

**Comment by luke86** [comment]
I just tried it and its my favourite way to play the game now. 
Thanks a lot!
