### ISSUE TITLE
Sorcer Striker Black Screen - doesn't attempt to assemble/load ROM

### ISSUE THREAD

**Issue by Restart-Point** [MiSTer-devel/Arcade-Raizing_MiSTer#18]
All the Garrega core games work fine for me except Sorcer Striker. Which just goes to a black screen and doesn't show any errors/warnings about the rom and it doesn't try to assemble/load the rom. Just stays on black screen. I have a single 128MB SDRAM. My MiSTer doesn't have any other issues I am aware of. I also checked the sstriker.zip ROM MD5 hash against one I got from MAME set 0.245 and it is correct. I also tried reverting to Garegga_20220725.rbf but still same issue with Sorcer Striker. I have compared MD5 hashes of MRA and RBF from update_all to latest GITHUB versions and they are all correct

**Comment by atrac17** [comment]
Run update _all again. The MRA has been updated.

**Comment by Restart-Point** [comment]
I have run update_all a few times yesterday/today and again just now 19:22 GMT.
Nothing was updated and Issue is still the same. thanks

**Comment by Restart-Point** [comment]
Sorcer Striker is working good. I appreciate  your quick responses!
