### ISSUE TITLE
Sorcer Striker - Raizing logo and character select sprites missing

### ISSUE THREAD

**Issue by Toryalai1** [MiSTer-devel/Arcade-Raizing_MiSTer#23]
In the 20220814 build of Sorcer Striker, the Raizing logo in the notice screen is missing: (Please ignore the weird screen shot, I don't know why it was screen shotted like that)
![20220814_131841-screen](https://user-images.githubusercontent.com/82502378/184534374-40a7c549-d30d-490f-b911-772ae2de6e1a.png)

It should look like this:

![Skärmavbild 2022-08-14 kl  13 22 27](https://user-images.githubusercontent.com/82502378/184534459-f4312fee-16b8-4374-8fbf-a6a015a47334.png)

Also, the character sprites in the character select screen are missing.
![20220814_131906-screen](https://user-images.githubusercontent.com/82502378/184534384-99f93ac9-6843-4666-8aa1-8f69b6879bbc.png)

It should look like this:

![Skärmavbild 2022-08-14 kl  13 24 13](https://user-images.githubusercontent.com/82502378/184534497-2d5dea46-f872-42cf-8a81-d2f4adb09981.png)

Thank you so much for the core!

**Comment by psomashekar** [comment]
Thanks,
Probably there's no sprite lag in this game, so I have to add an exception for this. What about kingdomgp?

**Comment by psomashekar** [comment]
by the way, I am not actively working on sorcer or kingdom in these builds as I don't have the real boards and I need confirmation of some details to proceed on the speed fix and other things as well that are issues.

**Comment by psomashekar** [comment]
after doing some investigation, it may be the way that the game wraps sprites around when there is overflow. Because when I play the game, it seems the left side sprites get cut off somewhat.

**Comment by psomashekar** [comment]
fixed.
