### ISSUE TITLE
Battle Garegga - Coin Error when inserting coin.

### ISSUE THREAD

**Issue by Toryalai1** [MiSTer-devel/Arcade-Raizing_MiSTer#27]
When dying, and during the 9-second countdown, if you press the insert coin button multiple times or spam it, you will get a coin error message. After a minute or so it will restart back to the title screen.

**Comment by psomashekar** [comment]
Yes, this is original behavior on the real board for all 3 games.

**Comment by birdybro** [comment]
As a bit of trivia and a sidenote, this kind of error occurs in multiple other original hardware arcade systems. Think of it almost as a "tilt" sensor equivalent to prevent misuse, it apparently was often intentional.
