### ISSUE TITLE
DIP Setting Screen Flip Not Implemented

### ISSUE THREAD

**Issue by wolfsoftgmbh** [MiSTer-devel/Arcade-Raizing_MiSTer#29]
Battle Garegga both on analog output and hdmi startup looking like mirrored some parts and later in game background errors and sprite trouble
thanks for all 
go on

**Comment by psomashekar** [comment]
The dip is not implemented in the core.

**Comment by psomashekar** [comment]
I had a bit of time, and this will appear in today's build.

**Comment by psomashekar** [comment]
done.

**Comment by wolfsoftgmbh** [comment]
On HDMI Output with Videosettings: Rotate Screen works in both directions. 
But on analog Output (CRT) DIP Setting didn`t work with Screen Flip: ON.
As i am a CRT user, i didn't want to turn the heavy beast 180 degress ;-)
GO ON, thanks for all

**Comment by wolfsoftgmbh** [comment]
After update all it works perfect on my CRT with DIP Setting Flip Screen on 
Many thanks GO ON!
Can't wait to see Truxton 2 on my CRT ;-)

**Comment by psomashekar** [comment]
please follow @atrac17 for the toaplan2 core which will include truxton 2 and many others. Thanks for the support.
