### ISSUE TITLE
Sound Issues ( Speed and ADPCM ) Kingdom Grandprix

### ISSUE THREAD

**Issue by PepAlacant** [MiSTer-devel/Arcade-Raizing_MiSTer#35]
Hello! I could test the last release and the sound is not corrected. It fluctuates and goes slower than normal.
The ADPCM is barely audible ( It happens in all the Raizing releases that use the same chip )

I played this game a lot in Sega Saturn, The Saturn version has the arcade OST in CD-DA.

There are a videos about how it should go in speed and adpcm volumes.

https://www.youtube.com/watch?v=zUmPTf8MLm4&t=245s
https://youtu.be/rW9jdkgUYQE

Thanks  for your great work

**Comment by psomashekar** [comment]
That's from the OST, and it looks like it has reverb added to it or something. But was the speed correct in the previous release or too fast? Mabe I think it is too slow.

You should compare to the real PCB when reporting issues, not the sega saturn version:
https://www.youtube.com/watch?v=8iIe8mbHLVc&ab_channel=TheObsoleteGeek

**Comment by PepAlacant** [comment]
The SS version's music is the arcade OST recorded in CD-DA. The music that sounds in SS version is the arcade one. The reverb is a problem of the video. In the previous releases the sound was too fast, and had fluctuations. Now the sound is too slow and has fluctuations too. The ADPCM is too weak and barely audible. I'm sorry but I cannot give the real PCB confirmation, I've played it and I can say the SS version has the same music.

Thanks for your great work.

**Comment by psomashekar** [comment]
I think the latest release may be too slow compared to last one. I think it may be somewhere between 4mhz and 3.375 in that case @atrac17 has the real board and will measure today when he gets time.

**Comment by PepAlacant** [comment]
Fantastic!

**Comment by psomashekar** [comment]
Try latest build. Made some adjustments.
