### ISSUE TITLE
Sorcer Striker music is too slow.  Start/Coin buttons are reversed in button map.

### ISSUE THREAD

**Issue by ConHuevosGuey** [MiSTer-devel/Arcade-Raizing_MiSTer#38]
As of 8/30/2022 release, the music is still playing too slow in Sorcer Striker, if I had to guess I'd say it's at 0.75x the actual speed it should be.

The start and coin button are also swapped when defining buttons, start is actually coin and coin is actually start.

**Comment by MaxSchultz** [comment]
Agreed re: the music

When I tap out the first stage music to the pcb (https://www.youtube.com/watch?v=9N_aYVEv2fY) I get ~150bpm and with the core I'm getting ~140bpm.

**Comment by psomashekar** [comment]
There was an issue with the pll in yesterday's build. I will create another build today.

**Comment by psomashekar** [comment]
Please don't create an issue for the start/ coin button thing. It's been opened many times before and this is done on purpose for compatibility with keyboard input devices.

**Comment by ConHuevosGuey** [comment]
Hello again, just wanted to make you aware the 08/25/22 release also seems to have the slow music issue.  The 08/24/22 release seems to have it close to correct but could possibly be too fast, but sounds much better.

**Comment by psomashekar** [comment]
> Hello again, just wanted to make you aware the 08/25/22 release also seems to have the slow music issue.  The 08/24/22 release seems to have it close to correct but could possibly be too fast, but sounds much better.

No that version was too fast. I think I may have fixed it. I compare the length of the intro music to the length of the PCB intro music and it seems to stop at the exact same place, so I think it's the correct speed. I'm fixing other issues at the moment, so the new build is slightly on hold.

**Comment by psomashekar** [comment]
ok new build out. it should fix this one hopefully.
