### ISSUE TITLE
Battle Bakraid - scroll layers disappear when free play dip is enabled

### ISSUE THREAD

**Issue by luke86** [MiSTer-devel/Arcade-Raizing_MiSTer#41]
Tried to play 2 Player mode today, but for some reason the background and some parts of the boss sprites in the first level were black or just not there. We then reset the Core and started in 1 Player Mode which worked and then we welt the second player join while the first level was running. Everything looked good until we reached level 3 where the background didnt load again.

While making screenshots for this bugreport it also happened to me that i didnt get the background loaded in level 1 when im only starting with 1 player.

Also i made sure that i got the newest update today by removing and redownloading the rbf and mra file via update_all but when i check the about section of the core it still claims its BAKRAID v20220729 (see screenshot).

I also briefly tried the other Raizing cores and looked like everything else works, we even finished Sorcer Striker in 2 Player Mode.
Hope my report helps, thanks for all your work.

Used Game Files:
Bakraid_20220902.rbf
Battle Bakraid - Unlimited Version (USA) (Tue Jun 8 1999).mra

Screenshots (Im not playing like this, the Mister streched the screenshots this way, but the problem is still recognizable):
1_intro:
![1_intro](https://user-images.githubusercontent.com/1627236/188240962-74614915-238f-4c8e-9c0d-4356c3f3e972.png)
2_2player_ship_screen:
![2_2player_ship_screen](https://user-images.githubusercontent.com/1627236/188240966-703321cf-34d3-4e5e-9774-487a9b1ff5fa.png)
3_2player_1st_level_no_background:
![3_2player_1st_level_no_background](https://user-images.githubusercontent.com/1627236/188240955-e1c15bfd-feab-4710-a2d2-05349e5c4f81.png)
4_2player_1st_boss_missing_sprites:
![4_2player_1st_boss_missing_sprites](https://user-images.githubusercontent.com/1627236/188240959-819909ce-883d-42d4-b988-2f23835c63d8.png)
5_Mister-About
![grafik](https://user-images.githubusercontent.com/1627236/188241390-f71474cb-e828-43d8-80fc-77c87af3a2a6.png)

**Comment by psomashekar** [comment]
hmm, so the problem only presents itself in 2 player mode? It looks like the scroll layers are missing, but objects seem OK.

**Comment by psomashekar** [comment]
Hmm, so I tried this on my end and I was able to start a 2 player game as normal and nothing disappeared. Can you please let me know how this came about?

**Comment by luke86** [comment]
Yesterday it happened every time i started the game by letting both players choose their ship in the ship choosing screen. Sometimes it happened also when i only started as 1 player.

Today i tried it again after deleting my rbf/mra/rom + the config for the game and now sometimes it works with 2 players starting and sometimes i still get the black background at the first level with the 2 players. It feels like a 50/50 chance now that it works after a cold boot.

Here is a Video i made just now, it shows me starting the game after i reset the core over the reset button in den menu. at the end of the video i also show what my video settings, dipswitches(should be standard settings) and the about screen look like.
https://photos.app.goo.gl/GvdZSnDPUMay4eeD7

**Comment by psomashekar** [comment]
Hmm, if it's not consistent it sounds like some compatibility issue with SDRAM. Although, the scroll layers thing I've seen disappear entirely with an improper dtack module. Mabe that plays a role in this, but not sure. I'll keep this issue open for now to see if others report the same thing. Thanks for letting me know.

**Comment by owlnonymous** [comment]
It happens on a one player game stage 3 consistently. New in today's update.

**Comment by psomashekar** [comment]
There really hasn't been any updates to Bakraid except for just changing the pll. I know people have 1ccd this, so it was working with the previous pll. Mabe I should just revert the build back to before?

**Comment by psomashekar** [comment]
> It happens on a one player game stage 3 consistently. New in today's update.

I just got up to stage 3 and did not see this happen. That's why I am saying, mabe it's only happening for some people?

**Comment by psomashekar** [comment]
@luke86 can you please try bakraid 20220904 build? Thanks.

**Comment by luke86** [comment]
I re-tested everything now with the newest build i got an hour ago from update_all.

2 Player Test:
I Tested the same way as before and i feel like it works more often now. I completely rebooted the Mister 5 Times and i got it working 3 out of 5 Times, so the Background in the first level was there. When i did not cold boot the Mister and just triggered reset in the Menu screen of the core it worked 4 out of 5 Times.

1 Player Test:
a) I found out that some Ships seem to make the bug occour more often than others. When i chose "Flame Viper" with the "Shot" Button so it doesnt change color i get the black background 4 out of 5 Times.

b) I tried to reach Stage 3 to see if the same things happen to me as to [owlnonymous](https://github.com/owlnonymous) but everything worked. When i got to Stage 4 (Desert) the background turned and stayed black though.

One Thing to note about Stages is, when ever i start the Game I get a different Stage order. The First level is always the same but after the first its always a different order. also when i chose the same ship with the same button at the beginning the order always changes for me. So stage 3 can be any level really. The good thing is at the top of the screen in Yellow letters the Stage name is written.

For me i only get the black background on the first Stage sometimes and i so far always got it in the "Desert" Stage.

c) One interesting thing is also that when i reset at a stage where the background is just black, as soon as i reset you can briefly see the background getting visible before the game resets.
See Video here: https://photos.app.goo.gl/Hg3BtHthB5JJ2Vyr9

**Comment by psomashekar** [comment]
Yea there are different branching paths and such. This problem has to do with dtack as far as I know, because I upgraded JTFrame and all my scroll layers disappeared completely. So I reverted it back and it seemed fine. But I guess there are cases when it disappears.

**Comment by psomashekar** [comment]
Yea there are different branching paths and such. This problem has to do with dtack as far as I know, because I upgraded JTFrame and all my scroll layers disappeared completely. So I reverted it back and it seemed fine. But I guess there are cases when it disappears.

The only possible way I can replicate this is if I change the dtack module in JTFrame with an upgraded one. So at least I have a baseline for my tests to see which things work.

**Comment by psomashekar** [comment]
I still can't replicate this with the original release. The only way I can do it is by intentionally breaking it. @luke86 what about the releases before, do any of them have the same behavior?

**Comment by lsnderick** [comment]
I have this problem when the game is set to freeplay only. Maybe this helps identify the issue.

**Comment by psomashekar** [comment]
> I have this problem when the game is set to freeplay only. Maybe this helps identify the issue.

You are right, it appears to have something to do with the free play dip.

**Comment by luke86** [comment]
Can confirm it works perfect when I change from free play mode to 1/1. I tried 10 times and also played until I reached The Desert stage and everything worked. Also tried 2 player mode a few times without a problem.

As soon as I changed back to free play mode it happened again. I tried with the newest update (6.september)

**Comment by psomashekar** [comment]
> Can confirm it works perfect when I change from free play mode to 1/1. I tried 10 times and also played until I reached The Desert stage and everything worked. Also tried 2 player mode a few times without a problem.
> 
> As soon as I changed back to free play mode it happened again. I tried with the newest update (6.september)

Thanks for that. In my investigation today, I found that the interface timing of the 68k to the z80 has bearing on this issue. I made some updates to the timing of the interface which either alleviates or completely eliminates the issue. At least I cannot replicate it anymore on my end. I could replicate it pretty much every time before with the free play dip on. I will release this today for testing.

**Comment by psomashekar** [comment]
ok this should be fixed with the latest release. At least I cannot replicate it anymore, but test and let me know.

**Comment by lsnderick** [comment]
After the latest update this problem reappeared for me unfortunately.
