### ISSUE TITLE
Sorcer Striker · Some SFX are low volume (or music too loud?)

### ISSUE THREAD

**Issue by MaxSchultz** [MiSTer-devel/Arcade-Raizing_MiSTer#42]
PCB video used for comparison: https://youtu.be/jwXV7dZFczM?t=28
Tested with different audio setups and headphones directly out of the MiSTer.

**SFX that seem to be too low**
Ship takeoff sound
Enemy death/explosion
Enemy shots
Player option shot
Player death
...

**SFX that seem OK**
Coin pickup
Power-up/magic book pickup
Enemy tank or turret armor hit/damage

Having a lot of fun with this core and already set some personal bests! Thanks for all your hard work.

**Comment by psomashekar** [comment]
It looks like the synth is like some really low value below the pcm, mabe 25% or so. Let me try with 25% for synth and 100% for pcm.

**Comment by psomashekar** [comment]
this should be fixed now for sorcer and kingdom. Thanks.
