### ISSUE TITLE
Garegga and other games listed as 20220729 release in about section even with latest builds. 

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/Arcade-Raizing_MiSTer#46]
Not sure why it keeps showing it as an older build. 

![Garegga](https://user-images.githubusercontent.com/36483667/188426730-4f639788-d770-47fe-95bc-fcca8a0fc63c.JPG)

![DSC00331](https://user-images.githubusercontent.com/36483667/188426071-06f58d68-1521-4af3-83a4-8918110921d2.JPG)

**Comment by birdybro** [comment]
It's because jotegos framework has special things in the qsf to handle this that need to be incremented each time

https://github.com/MiSTer-devel/Arcade-Raizing_MiSTer/blob/develop/bakraid.qsf#L130

**Comment by psomashekar** [comment]
Yea this is working properly as far as I know. I don't know what determines that date.

**Comment by atrac17** [comment]
Update the hex address in the cfgstr files.

**Comment by SegaSnatcher** [comment]
> It's because jotegos framework has special things in the qsf to handle this that need to be incremented each time (I think)
> 
> https://github.com/MiSTer-devel/Arcade-Raizing_MiSTer/blob/develop/bakraid.qsf#L130
> 
> Edit: actually it might be something else.
> 
> Check your `_Arcade/cores` folder to see if there are duplicates.

No duplicates.

**Comment by psomashekar** [comment]
Yea I have a tcl script mod that will do this in the cfgstr that I'm testing. Thanks @atrac17 .

**Comment by psomashekar** [comment]
fixed in next release.
