### ISSUE TITLE
Announcer sound barely audible Armed Police Batrider

### ISSUE THREAD

**Issue by GoldMister2** [MiSTer-devel/Arcade-Raizing_MiSTer#47]
Only Batrider has this issue. FX toggle and my setup does not change the issue.

**Comment by eturquin** [comment]
Seems like the Low to High FX Vol settings have been shifted, Low is the highest atm.

**Comment by psomashekar** [comment]
That was the previous build, I think it's reversed now, but still the options are out of order from the menus. The volume gain is from the board. The only thing I can do for different setups is allow to set the fm and PCM gain separately. Mabe I can do this as an enhancement.

**Comment by GoldMister2** [comment]
It is also the explosions, bomb attacks and death (when the players ship explodes) if that helps.
The music, the sound of the ships weapon charging and pickups are normal.

**Comment by psomashekar** [comment]
pull latest release. I set ym volume to 50% and pcm to 100. your fx level setting should be on "high" as a default.
