### ISSUE TITLE
Game reset loop and graphics corruption.

### ISSUE THREAD

**Issue by J3rUr0** [MiSTer-devel/Arcade-Raizing_MiSTer#5]
The game(s) restarts after 2-3 seconds after the initial test screen. 
There is also some graphics corruption.

I can do tests if you need it...

Arcade-Garegga_20220725.rbf
Arcade-Batrider_20220725.rbf
Arcade-Bakraid_20220725.rbf
128mb module

**Comment by hyp36rmax** [comment]
Sounds like SDRAM Timing. I had that issue with Battle Garegga with a RAM0 Bad and Kingdom GP Bad Rom Error. These are known.

**Comment by J3rUr0** [comment]
Now working correctly with the release:
Arcade-Batrider_20220726.rbf

**Comment by atrac17** [comment]
Very confused with it "rebooting", I did not experience this.

Made changes due to the same errors and tested for a few hours. Gave it a shot, apologies for the issues you are experiencing.

**Comment by J3rUr0** [comment]
> Very confused with it "rebooting", I did not experience this.
> 
> Made changes due to the same errors and tested for a few hours. Gave it a shot, apologies for the issues you are experiencing.

@atrac17
I dont have problems with the other cores. Tell me if you want to test something.
Thanks a lot for your dedication.

**Comment by J3rUr0** [comment]
After further investigation it appears that it was an overheating issue!
I am closing the issue as it is a specific issue with my setup.

Note: I still don't know why other cores worked fine...

**Comment by zakk4223** [comment]
Someone I know is having this exact issue, even with the new SDRAM parameters. Graphical glitches and then the core just resets. They are using a 128MB sdram module, not sure what versions etc. I'll update this with a link  to a twitch vod timestamp later that shows it happening to them

**Comment by atrac17** [comment]
> Someone I know is having this exact issue, even with the new SDRAM parameters. Graphical glitches and then the core just resets. They are using a 128MB sdram module, not sure what versions etc. I'll update this with a link to a twitch vod timestamp later that shows it happening to them

We've got it figured out. It's more than just SDRAM parameters. Still some more work to be done before anything can be pushed.
