### ISSUE TITLE
Sprites Missing in Sorcer/Kingdom due to fast object queue optimization in 9/13 Release 

### ISSUE THREAD

**Issue by PepAlacant** [MiSTer-devel/Arcade-Raizing_MiSTer#54]
The weapons as the green one playin with Chita (the girl) doesnt display the flare or weapon effect. It shows a little and buggy at the most left side of the screen.

it happens with the red fire, and I suppose it happens with other characters.

**Comment by psomashekar** [comment]
Do you have a screenshot?

**Comment by psomashekar** [comment]
fixed.
