### ISSUE TITLE
Not an issue but is there a reason batsugun isnt payable? 

### ISSUE THREAD

**Issue by theenemy-thd** [MiSTer-devel/Arcade-Raizing_MiSTer#57]
Not a bug or issue but just wondering why batsugun isn't playable?

**Comment by psomashekar** [comment]
Batsugun is a 1993 game made by Toaplan. As indicated by the title of this repo, and the readme, this core only supports specific games made by Raizing during this period and clearly states the names of the games. The Toaplan games made during the same period, aim to be supported by @atrac17 through another core, this one: https://github.com/atrac17/Toaplan2

**Comment by theenemy-thd** [comment]
Many thanks for the clarification 👍
