### ISSUE TITLE
Problem .. bad rom on all games that use the same core

### ISSUE THREAD

**Issue by bonna79** [MiSTer-devel/Arcade-Raizing_MiSTer#58]
Although I have always updated the mister fpga, equipped with a 128 mb 2-chip ram, bat rider initially went, now it no longer gives me errors at the first start.
Bad rom screen appears.
I attach photos of Batrider

![IMAGE 2022-10-04 16:35:05](https://user-images.githubusercontent.com/70318818/193848702-9e6c685c-e2e2-402c-957f-9efa1972f960.jpg)
![IMAGE 2022-10-04 16:35:10](https://user-images.githubusercontent.com/70318818/193848685-a49f27f8-6100-4792-9868-73df91de377c.jpg)
![IMAGE 2022-10-04 16:35:13](https://user-images.githubusercontent.com/70318818/193848691-ae6fa098-bff2-4c19-b0bd-b8b5a504a41a.jpg)
![IMAGE 2022-10-04 16:35:16](https://user-images.githubusercontent.com/70318818/193848714-788d6ada-4f1e-411e-9f0b-78360ce59195.jpg)
![IMAGE 2022-10-04 16:35:18](https://user-images.githubusercontent.com/70318818/193848718-6ef8c23d-ba56-41fa-bc6d-5e640078d3fb.jpg)

https://user-images.githubusercontent.com/70318818/193849723-96c6c06c-80f6-4e35-b7a3-794ea848bb8a.mp4

While
[Sorcer Striker]
[Kingdom Grandprix]
[Battle Garegga]
[Battle Bakraid]

as soon as they are executed, the word bad rom appears

I repeat mister updated today at 15:35 Italy

**Comment by psomashekar** [comment]
I believe these are issues concerning the sdram or rom zip, not the core itself as it has come up many times in the past. For these questions, please ask in discord and folks can help out. Thanks.
