### ISSUE TITLE
Glitches...

### ISSUE THREAD

**Issue by IcarusFW** [MiSTer-devel/Arcade-Raizing_MiSTer#60]
I've ran into a couple of visible layer priority issues on the most recent cores for Bakraid (Arcade-Bakraid_20221006.rbf) and Mahou Daisakusen (Arcade-Garegga_20220914.rbf):

- In Mahou/Sorcer Striker, in stage 3 in particular, the small fish enemies and giant fish heads at the end of the stage appear to have the wrong layer priority, and appear on top of the stage wall when they appear - video: https://clips.twitch.tv/PrettyEsteemedOkapiPJSugar-It3Hb4zWn0cF_nrg
- In Bakraid, the background layer for Naval can random fail to load with the correct layer priority after defeating the previous stage boss, and as a result the whole stage background is black - video: https://clips.twitch.tv/WiseDeafOstrichBCWarrior-snzTlcVzA7rZDd2V (note that I normally play with Naval stage as stage 3, so it may either happen to another stage as stage 3, or it may be specific to the Naval stage itself.) 

This is with a brand-new 128MB v2.9 RAM module, and with a completely clean reinstall of both cores, .mra files, and ROM files.

**Comment by lsnderick** [comment]
Not sure if related, but after latest update the bug with Bakraid scroll layers disappearing with free play dip is back again for me :(

**Comment by psomashekar** [comment]
@IcarusFW for Bakraid, did this happen with the last release? Mabe I need to roll back the mister version as the solution for pocket is not entirely applicable.

**Comment by psomashekar** [comment]
Yea sorcer has weird priority issues. I implemented a fix that corrected the 2nd boss, but I guess that's not working in other cases like the castle walls. I'll think about it.

**Comment by psomashekar** [comment]
@lsnderick I reverted the bakraid release that was broken, so this should work like before. I won't mess with it on mister. I will test more on my pocket version. I think the timings are different because I am using a different clock for that.

**Comment by IcarusFW** [comment]
> @IcarusFW for Bakraid, did this happen with the last release? Mabe I need to roll back the mister version as the solution for pocket is not entirely applicable.

It happened with current and previous release, as I tested them both out on stream.

**Comment by psomashekar** [comment]
thanks @IcarusFW , I will look into it.

**Comment by psomashekar** [comment]
@IcarusFW how often does this happen for you on the last september build? I tried the railroad and then the naval stage, and I am not able to replicate this on that. I have heard of this issue happening prior to that build though.

**Comment by psomashekar** [comment]
[bakraid.zip](https://github.com/MiSTer-devel/Arcade-Raizing_MiSTer/files/9743369/bakraid.zip)
@IcarusFW would you mind trying this to see if it makes the issue better or worse? @lsnderick as well.

**Comment by lsnderick** [comment]
> [bakraid.zip](https://github.com/MiSTer-devel/Arcade-Raizing_MiSTer/files/9743369/bakraid.zip) @IcarusFW would you mind trying this to see if it makes the issue better or worse? @lsnderick as well.

Did a quick test playthrough of a normal course, seems to be working good for me with this build.

**Comment by IcarusFW** [comment]
> @IcarusFW how often does this happen for you on the last september build (0913)? I tried the railroad and then the naval stage, and I am not able to replicate this on that. I have heard of this issue happening prior to that build though.

I was on 0913 originally, and could get it to happen once every few credits. Updated on stream to the 1006 build, and it still happened once every few credits.

I'll take a look at the new build you posted later and will report my findings.

**Comment by IcarusFW** [comment]
Okay, so a quick update after testing the Bakraid and Garegga cores again.

Bakraid (current public ver., updated via *update_all* today):

- Still exhibits the issue with the vanishing background - tested the public core with all manner of stage orders today, and always seem to get it when going Forest > Railroad > Naval for some reason, and not with Forest > Railroad > whatever else. (Clip from today: https://clips.twitch.tv/ScrumptiousYummyDonutKreygasm-0FQ9AnRsXxuQu13z)
- Found a new and pretty weird glitch where square and rectangular chunks from the Cloud stage are missing. This is most noticeable when a grey square occasionally drops down the screen during play. (Clip from today: https://clips.twitch.tv/EvilGenerousGerbilPanicVis-0PmzuB6rEnFYQJ0N)

Bakraid (test core linked above: https://github.com/MiSTer-devel/Arcade-Raizing_MiSTer/files/9743369/bakraid.zip)

- Also exhibits the vanishing background issue with the above stage order, appears to affect not just the background layer but anything else on that layer if you leave it, eg title screen, high score table, attract sequence. (Clip from today: https://clips.twitch.tv/PunchyBashfulEggKreygasm-b9LGmK8sHGV-8Sdp)
- High score table during the attract sequence appears to have a small amount of glitching on it. (Clip from today: https://clips.twitch.tv/BlazingAbstruseSnailTakeNRG-HfXHOO_FTXoE0tld)

Garegga (current public ver.)

- Some very noticeable glitching on large explosions, most obviously on the stage 3 and 4 boss, maybe more. Manifests as a bunch of vertical noise that doesn't appear on the arcade version (checked on PCB).
stage 3: https://clips.twitch.tv/DepressedFriendlyWaffleHassanChop-nR3XzCqsJcsb_EBs
stage 4: https://clips.twitch.tv/ConfidentBadDugongWoofer-tRWuBVtu_V3DBKc0

Haven't had time to go through Batrider fully yet, and Mahou doesn't seem to have any other issues outside of that stage3 one noted earlier.

Full 4.25hr VOD of testing today: https://www.twitch.tv/videos/1620824594

**Comment by psomashekar** [comment]
thanks @IcarusFW , I have a fix for sorcer striker (and potentially other games with priority issues) coming today. a bit was cut off the priority level.

I personally cannot replicate the bakraid issue. If it happens for me, it will happen during the attract sequence, so I wonder if it is timing with the sdram? The glitching is definitely due to sdram though. I changed the clock to alleviate it for different types of sdram, but it might not work 100% with everything out there.

**Comment by psomashekar** [comment]
ok I think I may have found a way to replicate the bakraid issue. will think on this one for a bit to see if I have any ideas as to what may be causing it. Interestingly enough, resetting the core seems to bring back all the scroll layers.

**Comment by psomashekar** [comment]
I think this bakraid issue with the scroll layers depends on which character you choose as well, because I can never replicate it with the ships in the top row. I have been able to replicate it every time with flame viper. Is this your experience as well @IcarusFW ?

**Comment by IcarusFW** [comment]
> I think this bakraid issue with the scroll layers depends on which character you choose as well, because I can never replicate it with the ships in the top row. I have been able to replicate it every time with flame viper. Is this your experience as well @IcarusFW ?

Yes, I primarily play with the Flame Viper and usually get the glitch to happen a few times a session.

**Comment by psomashekar** [comment]
ok @lsnderick @IcarusFW 
I think I got it. Please try this build. I can no longer replicate with flame viper on either free play or regular coin play.
[bakraid.zip](https://github.com/MiSTer-devel/Arcade-Raizing_MiSTer/files/9759745/bakraid.zip)

**Comment by lsnderick** [comment]
I don't have time for extensive testing currently, but after a quick run seems to look good.

**Comment by IcarusFW** [comment]
I'll take a look at the new versions tonight.

**Comment by IcarusFW** [comment]
Okay, a quick update:

- Mahou - Stage 3 layer priority bug fixed. Haven't seen anything else so far (but need to get into the last stage to check).
- Shippu Mahou - Played this a few days ago and didn't see anything, just for reference.
- Batrider - Haven't gone through the whole game yet, but so far haven't noticed anything major. Still need to do a run triggering the extra bosses to check them, but the whole of Normal Course with a regular ship didn't show anything weird.
- Garegga - Vertical explosion glitch is still there: https://www.twitch.tv/videos/1622359200?t=2h37m52s 
- Bakraid - Cloud background squares glitch is still there: https://www.twitch.tv/videos/1622359200?t=3h19m52s - I did also manage to trigger the background disappearing glitch with Railroad on stage 4 and Desert on stage 5 (using Flame Viper: https://www.twitch.tv/videos/1622359200?t=1h22m42s), however this may have been on an older core, as I still had the test core on my MiSTer along with the one that gets pulled from update_all and only remembered to get rid of it for the second set of runs at the end of the stream.

I'm travelling for a week from tomorrow, and won't be able to test the cores until I get back.

**Comment by psomashekar** [comment]
Thanks a lot for testing. I haven't investigated the other minor graphical glitches yet. I'll take a look at the video in detail and see what it could be.

**Comment by psomashekar** [comment]
> Okay, a quick update:
> 
> - Mahou - Stage 3 layer priority bug fixed. Haven't seen anything else so far (but need to get into the last stage to check).
> - Shippu Mahou - Played this a few days ago and didn't see anything, just for reference.
> - Batrider - Haven't gone through the whole game yet, but so far haven't noticed anything major. Still need to do a run triggering the extra bosses to check them, but the whole of Normal Course with a regular ship didn't show anything weird.
> - Garegga - Vertical explosion glitch is still there: https://www.twitch.tv/videos/1622359200?t=2h37m52s 
> - Bakraid - Cloud background squares glitch is still there: https://www.twitch.tv/videos/1622359200?t=3h19m52s - I did also manage to trigger the background disappearing glitch with Railroad on stage 4 and Desert on stage 5 (using Flame Viper: https://www.twitch.tv/videos/1622359200?t=1h22m42s), however this may have been on an older core, as I still had the test core on my MiSTer along with the one that gets pulled from update_all and only remembered to get rid of it for the second set of runs at the end of the stream.
> 
> I'm travelling for a week from tomorrow, and won't be able to test the cores until I get back.

I was able to clear the entire game with flame viper with stage 4 as the railroad and stage 5 as the desert, so I think mabe it must have been an older build you used there. But let me know if anything weird comes up...

**Comment by psomashekar** [comment]
The vertical explosion thing happens on the end boss in batrider as well. What's happening (I think) is that some of the slices of the tiles that make up the explosion end up being out of order priority wise. At least that's what I noticed anyway. Will take a look into this. I think I had this come up before too for Garegga when I was testing.

**Comment by IcarusFW** [comment]
Just got back from my trip. I'll try to find some time this week to give the new cores a quick run through.

**Comment by blisstik** [comment]
The latest bakraid just simply glitches out to black screen. The other 2 latest cores work just fine.

**Comment by psomashekar** [comment]
> The latest bakraid just simply glitches out to black screen. The other 2 latest cores work just fine.

yea not sure, I use it personally and built for both pocket and mister and both work fine. Please check your setup.

**Comment by blisstik** [comment]
> > The latest bakraid just simply glitches out to black screen. The other 2 latest cores work just fine.
> 
> yea not sure, I use it personally and built for both pocket and mister and both work fine. Please check your setup.

I had the 1017, the 1018 one worked.

**Comment by IcarusFW** [comment]
Okay did some testing tonight on all of the cores, and got some time in on
Bakraid, Batrider, Garegga and Mahou.
Happy to report I haven't seen any major issues at all in the four hours of
testing tonight. I'll naturally keep testing as we go (plus it's a good
excuse to get back into practice with these games), but for now I think
that they're in a good state.

**Comment by psomashekar** [comment]
> Okay did some testing tonight on all of the cores, and got some time in on
> Bakraid, Batrider, Garegga and Mahou.
> Happy to report I haven't seen any major issues at all in the four hours of
> testing tonight. I'll naturally keep testing as we go (plus it's a good
> excuse to get back into practice with these games), but for now I think
> that they're in a good state.
> 

Thanks very much for testing these on your stream! As always, please let me know if you encounter anything and I can investigate and fix.
