### ISSUE TITLE
Autofire in Garegga

### ISSUE THREAD

**Issue by eturquin** [MiSTer-devel/Arcade-Raizing_MiSTer#8]
Would it by any chance be possible to add autofire rate (not talking about Mister's generic autofire system, but the one built into the game) as an option in the OSD menu, for Battle Garegga? Switching rates is quite critical in trying to finish the game, given the rank system. Cheers!

**Comment by psomashekar** [comment]
Zakk may know something about it. But in any case, autofire rate has nothing to do with the core itself, but the MiSTer system. inputs are passed to the game as is, so we cannot actually control inputs the other way around - they get passed to the game, and the game processes them. I would reach out to him as there's been some talk about this in the channel as I saw, but this will not be handled by this core.

**Comment by eturquin** [comment]
Fair enough, although I was talking about the autofire built into the game (not the generic MiSTer one, that can be applied to any game and button). When holding the first button down, there is an autofire, whose rate can be set to different values; the higher the frequency, the more it increases the rank, so it is common to set it to 10Hz, which is the max value that still has the minimal impact on the rank, then increasing it at a later stage into the game when rank is not so important anymore, but fire power is! :) Taken from Shmups wiki (https://shmups.wiki/library/Battle_Garegga): "arcade cabinets often install a dial for selecting the rate of auto-fire".

**Comment by eturquin** [comment]
(Btw, this was mentioned in the original repo too: https://github.com/psomashekar/pr4m0d-MISTer-bin/issues/23)

**Comment by psomashekar** [comment]
Based on what I see in that wiki, if the autofire rate is selected by pressing a button at a certain rate, it means it can be achieved perhaps through a rom hack of some kind to set the rate outside of the normal conventional way. I would follow up with zakk on this, he is the expert in this area. But, if you have to keep going to the menu to select the auto fire rate while you are playing the game, I don't think that's a good way to achieve this. Mabe some alternative button combination or something may be best? Not sure, check with Zakk please.

**Comment by eturquin** [comment]
Will do! And double thanks, for the fast replies to this thread, and more importantly for all your amazing work on the Toaplan cores, those are a dream come true! ^_^

**Comment by psomashekar** [comment]
@atrac17 says mabe some patch in the MRA can achieve this? Not sure. Sorry.

**Comment by eturquin** [comment]
Btw, what would be the best way to get in touch with Zakk about this? (Zakk, are you reading this? ;))
Also, setting this rate in the menu wouldn't be such a big issue, since we can pause the game, and this is not something that you do very often anyway (maybe once or twice in a complete run... and prob. never if you can't get past the first few levels).
The M2 release on PS4 has a dedicated button to cycle through the different autofire frequencies, but you can also see the current frequency value on screen: if you don't have the later, it's probably safer to set it in the menu.

**Comment by zakk4223** [comment]
I added autofire select to my garegga rom modifications. Start+B will increase autofire rate in the same increments as M2 port. You can't increase to the 'hidden' 60hz via this method, though. You'll have to enable the stage edit dip to see the current autofire rate. (I might change this in the future and always show autofire rates)

You can use the MRA in this directory: https://github.com/zakk4223/battle-garegga-patches/tree/master/mister

**Comment by luke86** [comment]
I just tried it and its my favourite way to play the game now. 
Thanks a lot!

**Comment by psomashekar** [comment]
Thanks @zakk4223.
