### ISSUE TITLE
Armed Police Batrider displays only in black and white on a CRT when using a YC active encoder board.

### ISSUE THREAD

**Issue by thericeking** [MiSTer-devel/Arcade-Raizing_MiSTer#80]
Armed Police Batrider displays only in black and white on a CRT when using a YC active encoder board.

**Comment by atrac17** [comment]
That's because the modified jotego framework does not have the Y/C module by @MikeS11. I assume you are using the board provided by misteraddons.

**Comment by MikeS11** [comment]
I have forked cores that have yc support for most cores that do not have the old framework, you just need to enable it in the update all script.

**Comment by thericeking** [comment]
> That's because the modified jotego framework does not have the Y/C module by @MikeS11. I assume you are using the board provided by misteraddons.
Yes, I’m using the Y/C module by misteraddons. Forgive my ignorance but is this not the correct place to report issues.

**Comment by thericeking** [comment]
> I have forked cores that have yc support for most cores that do not have the old framework, you just need to enable it in the update all script.

I’ll have a look there. Thank you @MikeS11

**Comment by thericeking** [comment]
@atrac17  I looked at the cores that Jotego worked on and I didn't see Armed Police Batrider as one of his cores. I saw Armored Warriors on his list. https://github.com/jotego/jtcores_mister/tree/main/_Arcade

**Comment by atrac17** [comment]
> @atrac17 I looked at the cores that Jotego worked on and I didn't see Armed Police Batrider as one of his cores. I saw Armored Warriors on his list. https://github.com/jotego/jtcores_mister/tree/main/_Arcade

This uses JOTEGO's framework. It's not a JOTEGO core.

**Comment by psomashekar** [comment]
Sorry, just now seeing this. Does this need an extra module or something integrated to support? Can @MikeS11 add it?

**Comment by psomashekar** [comment]
> @atrac17 I looked at the cores that Jotego worked on and I didn't see Armed Police Batrider as one of his cores. I saw Armored Warriors on his list. https://github.com/jotego/jtcores_mister/tree/main/_Arcade

I am the core author. All my cores use JTFrame, but that's just a framework template. Jose is not involved in developing the cores I make.
